# Generated by Django 5.1.5 on 2025-02-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_heroblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='hero_images/', verbose_name='Фоновое изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Hero блок',
                'verbose_name_plural': 'Hero блоки',
            },
        ),
    ]
