# Generated by Django 5.1.5 on 2025-02-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diplom/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Diplom',
                'verbose_name_plural': 'Diplom',
            },
        ),
    ]
